name: Test Azure OpenAI response

on:
  workflow_dispatch:           # run only when you click “Run workflow”

jobs:
  response-test:
    runs-on: ubuntu-latest
    environment: responses     # pulls in the secrets already in that env

    steps:
      - name: ⬇️ Check out repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-dotenv

      # ─────────────   CORE TEST STEP   ─────────────
      - name: 🧪 Run script & build report
        id: test
        shell: python            # <<< everything below is pure Python
        env:
          AZURE_OPENAI_API_KEY:        ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_V1_API_ENDPOINT: ${{ secrets.AZURE_OPENAI_V1_API_ENDPOINT }}
          AZURE_OPENAI_API_MODEL:       ${{ secrets.AZURE_OPENAI_API_MODEL }}
        run: |
          import datetime, json, pathlib, subprocess, sys

          # run the existing file and capture its stdout / exit code
          proc = subprocess.run(
              [sys.executable, "responses-basic-aoai-v1.py"],
              capture_output=True, text=True
          )
          output      = proc.stdout.strip()
          error_code  = proc.returncode
          passed      = bool(output) and error_code == 0   # tweak if you need stricter logic

          result = {
              "run_timestamp_utc": datetime.datetime.utcnow()
                                  .isoformat(timespec="seconds") + "Z",
              "output": output,
              "pass": passed,
              "error_code": error_code,
          }

          pathlib.Path("aoai_test_result.json").write_text(
              json.dumps(result, indent=2), encoding="utf-8"
          )

          # Fail the job if the test failed
          if not passed:
              sys.exit(error_code or 1)

      # ─────────────   UPLOAD REPORT   ─────────────
      - name: 📤 Upload test artifact
        if: always()               # still run even if the step above failed
        uses: actions/upload-artifact@v4
        with:
          name: aoai-response-test
          path: aoai_test_result.json
